name: Test

on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: install dependences
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: pytest
        run: pytest
